### ISSUE TITLE
Content-type doesn't create new entry

### ISSUE THREAD

**Issue by dwest-ee** [rv-kip/express-redis-cache#21]
Hi,

An initial request with Accept:text/html header, responding with a Content-Type:text/html, then a subsequent request to the same route with Accept:application/json, responding with Content-Type:application/json doesn't create a new entry.

**Comment by co2-git** [comment]
Hi,

Can you provide your code?

**Comment by rv-kip** [comment]
@dwest-ee, can you provide some code that demonstrates the issue?

**Comment by rv-kip** [comment]
Closing due to lack of information.
