### ISSUE TITLE
ENV VAR to disable caching

### ISSUE THREAD

**Issue by pwmckenna** [rv-kip/express-redis-cache#30]
would be nice to be able to toggle this using an environment var. I'd be happy to provide a pull request if there's interest.

**Comment by co2-git** [comment]
Hey Patrick! PRs are always welcome :D Let me know if you have any
questions regarding code! Cheers!

**Comment by ScheerMT** [comment]
Couldn't something like this already be accomplished through the conditional caching feature?

```
app.get('/user',

  // middleware to decide if using cache
  // THIS IS NOT TESTED
  function (req, res, next) {
    // Use only cache if user not signed in
    if (process.env.NODE_ENV !== 'Production') {
        res.use_express_redis_cache = false;
    }

    next();
    }.

  cache.route(), // this will be skipped if user is signed in

  function (req, res) {
    res.render('user');
    }
  );
```

Going further you could define an array with the environment check function and cache.route() and simply call that array inside of your route to clean things up. 

I am mainly writing this out for anyone else looking to a solution and I think it would be worth while to add an additional option to include the environment variable to switch the caching on or off.

**Comment by rv-kip** [comment]
See `examples/example.js` in v0.2.0 release. Hopefully that will work for your needs.
