### ISSUE TITLE
Mapping missmatch with key and content - Caching different pages for different urls

### ISSUE THREAD

**Issue by kiranreddyzivame** [rv-kip/express-redis-cache#37]
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> TypeError: Cannot set property 'name' of null
>     at /var/www/mobile2/node_modules/express-redis-cache/lib/ExpressRedisCache/get.js:45:27
>     at b (domain.js:177:20)
>     at b (domain.js:183:18)
>     at try_callback (/var/www/mobile2/node_modules/redis/index.js:592:9)
>     at RedisClient.return_reply (/var/www/mobile2/node_modules/redis/index.js:685:13)
>     at ReplyParser.<anonymous> (/var/www/mobile2/node_modules/redis/index.js:321:14)
>     at ReplyParser.emit (events.js:95:17)
>     at ReplyParser.send_reply (/var/www/mobile2/node_modules/redis/lib/parser/javascript.js:300:10)
>     at ReplyParser.execute (/var/www/mobile2/node_modules/redis/lib/parser/javascript.js:211:22)
>     at RedisClient.on_data (/var/www/mobile2/node_modules/redis/index.js:547:27)
> error: Forever detected script exited with code: 7
> error: Script restart attempt #2

**Comment by co2-git** [comment]
Hey @kiranreddyzivame, thanks for the report. Unfortunately this project is discontinued as I don't have time for it :(
Cheers

**Comment by rv-kip** [comment]
@kiranreddyzivame, can you provide the url with params you were using when that error occurred?
