### ISSUE TITLE
Maintenance...

### ISSUE THREAD

**Issue by rv-kip** [rv-kip/express-redis-cache#38]
I'll maintain the project if you want to transfer to me.

**Comment by co2-git** [comment]
Sure Kip! Thanks :) I'll do it right now

**Comment by co2-git** [comment]
It says "rv-kip/express-redis-cache already exists". I guess it's your fork. What should we do? Should you delete your fork?

**Comment by rv-kip** [comment]
I renamed the fork. `express-redis-cache` should be available now.

**Comment by co2-git** [comment]
cool:) Also, what is your NPM username so I can make you an owner, so that you can publish any changes to the NPM repo?

**Comment by co2-git** [comment]
Trying to transfer once more the Githup repo to you, now getting "rv-kip already has a repository in the co2-git/express-redis-cache network". Could it be that you have to delete your fork altogether?

**Comment by rv-kip** [comment]
OK. I've deleted the fork. Give it another try.

**Comment by co2-git** [comment]
done :) what is your npm username so I can give you ownership of the module in npm?

**Comment by rv-kip** [comment]
rv-kip

**Comment by co2-git** [comment]
cool, I've added you as owner :+1:

**Comment by co2-git** [comment]
well that's it on my side I think. Let me know if I'm missing something

**Comment by ScheerMT** [comment]
Just came across this library. Thank you for creating this in the first place and hope to see it's stability and functionality be expanded and maintained :+1:

**Comment by rv-kip** [comment]
Thanks @co2-git!
