### ISSUE TITLE
Can't get binary content to be cached

### ISSUE THREAD

**Issue by tkrugg** [rv-kip/express-redis-cache#51]
If my route returns a binary file, the cache seems to simply ignore it, [as far as I can tell](https://github.com/rv-kip/express-redis-cache/blob/master/lib/ExpressRedisCache/route.js#L180).

This module was probably written to target caching of dynamic content, not static content (which most binaries are served as). Yet there are two use cases where you might want to have caching for binary files:
- if the file is generated server side, through some heavy operation.
- if the file is obtained through a http proxy

It should be easy to do with a little `buffer.toString("hex")` but the module doesn't allow to transform the response before it stores it and after it retrieves it.

**Comment by krazyjakee** [comment]
#66
