### ISSUE TITLE
Type option seems to not be taken into account

### ISSUE THREAD

**Issue by ghislaindj** [rv-kip/express-redis-cache#52]
As explained here https://github.com/rv-kip/express-redis-cache#content-type I tried to use the type config to force content type.

But it doesn't work : in fact I've searched the code to understand where it's used, and it seems to be never use. I think it should be use there : https://github.com/rv-kip/express-redis-cache/blob/master/lib/ExpressRedisCache/route.js#L186

Thanks a lot in advance,

Ghislain

**Comment by krazyjakee** [comment]
#66
