### ISSUE TITLE
expressRedisCacheName __fileName and __line don't exist

### ISSUE THREAD

**Issue by Loksly** [rv-kip/express-redis-cache#53]
There is a bug on:
https://github.com/rv-kip/express-redis-cache/blob/master/lib/ExpressRedisCache/route.js#L66
https://github.com/rv-kip/express-redis-cache/blob/master/lib/ExpressRedisCache/route.js#L102

Neither __fileName, nor __line, exist at all. The first one should be __filename and the __line doesn't exist. Check nodejs magic globals: https://nodejs.org/api/globals.html

Use expressRedisCacheName deprecated attribute to check. (Note you are using a domain.)

Thanks for your code.

**Comment by krazyjakee** [comment]
fixed in v2
