### ISSUE TITLE
Cache should preserve original response status code 

### ISSUE THREAD

**Issue by codeocelot** [rv-kip/express-redis-cache#54]
You've got a wonderful project here, but I notice results returned from the cache are always sent as 200, even if the original response is a 501 (Not Implemented) or what have you.  

At first glance, it wouldn't be too hard to include a field in your entry model to include the original response.  

Would you be open to accepting a pull request if I built out this feature?

**Comment by loganfuller** [comment]
+1

**Comment by co2-git** [comment]
sure, fire up your pull request! :)

**Comment by artursudnik** [comment]
Here https://github.com/rv-kip/express-redis-cache/issues/43 some work already done is mentioned.
