### ISSUE TITLE
Effect of caching route in redis using express-redis-cache

### ISSUE THREAD

**Issue by KaustubhYK** [rv-kip/express-redis-cache#57]
It is question not issue,what we are achieving from performance perspective by caching route into redis?
I got this question because I am working on application & I am caching route.
So during development,it becomes tedious to debug as code is getting cache in redis.

**Comment by co2-git** [comment]
Hey mate! You can actually disable caching when in dev: `res.
use_express_redis_cache = app.get('env');`

On Thu, Mar 10, 2016 at 3:07 AM, Kaustubh Kulkarni <notifications@github.com
