### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by ImanMh** [rv-kip/express-redis-cache#69]
When I run the `npm install express-redis-cache` command I get the following error and no directory is created in my node_modules. 

```
npm WARN package.json express-redis-cache@1.0.0 No description
npm WARN package.json express-redis-cache@1.0.0 No repository field.
npm WARN package.json express-redis-cache@1.0.0 No README data
npm WARN install Refusing to install express-redis-cache as a dependency of itself
```

**Comment by rv-kip** [comment]
I believe you are running `npm install express-redis-cache` inside a directory called `express-redis-cache` which has already been provisioned with `npm init`.  Change the name of the parent directory.

**Comment by ImanMh** [comment]
That was exactly it. Thanks I didn't know that.
