### ISSUE TITLE
redis unavailability crashing 

### ISSUE THREAD

**Issue by emckean** [rv-kip/express-redis-cache#74]
Hi! The README suggests that redis unavailability won't crash the app: "Should the redis become unavailable, the express-redis-cache object will emit errors but will not crash the app. Express.js requests during this time will be bypass cache and will return fresh data." 

Unfortunately, I'm not seeing this -- when I stop my local redis from running, I get 

```
cache { [Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

I am calling it like so, from an external (not in app.js) routes file: 

```
//cache
var cache = require('express-redis-cache')({
  host: config.redisHost, port: config.redisPort
  });

cache.on('error', function(error){
  console.error("cache", error);
});
...
routes.get('/fragments/flickr/:word', cache.route({expire: 86400}), fragments.flickr);
```

Any idea how to handle an unavailable redis? The graceful failure was one of the main selling points of express-redis-cache. :)

**Comment by krazyjakee** [comment]
#84
