### ISSUE TITLE
Redis Connection to localhost:6379 Failed

### ISSUE THREAD

**Issue by zaeem-bin-rehman** [rv-kip/express-redis-cache#80]
I'm new Express, and just created a basic app and trying to integrate the Redis cache for Express from [npm](https://www.npmjs.com/package/express-redis-cache)

When I install and add the module in the app, and run the appp it gives the error described on the screenshot.

![screenshot_4](https://cloud.githubusercontent.com/assets/5284439/21452052/f1492bae-c925-11e6-9346-6022393e5d29.png)

Express Ver:   4.14.0

**Comment by bsyk** [comment]
Are you running the Redis server on the same machine?
You can download it from https://redis.io/download

**Comment by zaeem-bin-rehman** [comment]
@bsyk 
Sorry for a very late reply, but that solved my problem.

**Comment by Mode7James** [comment]
It would be great to suppress the crash if Redis is not started or installed, per this issue:  https://github.com/rv-kip/express-redis-cache/issues/84.  I tried wrapping the route() call in a try/catch but still it crashes the app if not available at startup.

**Comment by weisjohn** [comment]
@ZaeemR please close this issue
