### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 disconnected listeners added

### ISSUE THREAD

**Issue by LiorRabin** [rv-kip/express-redis-cache#85]
**Hello,**
**any help would be appreciated regarding following issue**

**I'm using express and node 4.4.6 and this is how I've initialized the module:**
`var opts = {
    host: app.config.get('redis_host'),
    port: parseInt(app.config.get('redis_port') || '6379', 10),
    prefix: app.config.get('express_redis_cache_prefix') || 'colucommunity:cache:'
  }
  console.log('cache options', opts)
  app.cache = require('express-redis-cache')(opts)
  app.use(function(req, res, next) {
    res.use_express_redis_cache = app.config.get('express_redis_cache_enabled') === 'true'
    next()
  })
  app.cache.on('connected', function() {
    console.log('Cache is connected !')
    cb()
  })
  app.cache.on('disconnected', function() {
    console.warn('Cache is disconnected !')
  })
  app.cache.on('error', function(err) {
    console.error('Cache error:', err)
  })
  app.cache.on('message', function(msg) {
    console.log('Cache message:', msg)
  })`

**than on our server I get following error in log (I don't get that locally on my laptop):**
`
» 21 Mar 2017 17:52:25.187 (node) warning: possible EventEmitter memory leak detected. 11 disconnected listeners added. Use emitter.setMaxListeners() to increase limit.
» 21 Mar 2017 17:52:25.187 at ExpressRedisCache.addListener (events.js:239:17)
» 21 Mar 2017 17:52:25.187 at expressRedisCache_Middleware (/var/app/current/node_modules/express-redis-cache/lib/ExpressRedisCache/route.js:94:14)
» 21 Mar 2017 17:52:25.187 at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
» 21 Mar 2017 17:52:25.187 at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
» 21 Mar 2017 17:52:25.187 at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
» 21 Mar 2017 17:52:25.187 at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
» 21 Mar 2017 17:52:25.188 at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
» 21 Mar 2017 17:52:25.188 at cleanup (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:377:54)
» 21 Mar 2017 17:52:25.188 at allowCache (/var/app/current/modules/global.js:774:7)
» 21 Mar 2017 17:52:25.188 at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
» 21 Mar 2017 17:52:25.188 at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
» 21 Mar 2017 17:52:25.188 at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
» 21 Mar 2017 17:52:25.188 at next (/var/app/current/node_modules/express/lib/router/route.js:137:13)
» 21 Mar 2017 17:52:25.188 at Route.dispatch (/var/app/current/node_modules/express/lib/router/route.js:112:3)
» 21 Mar 2017 17:52:25.188 at Layer.wrappedHandle (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:598:19)
» 21 Mar 2017 17:52:25.188 at dispatch (eval at wrapHandle (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:1:0), <anonymous>:4:28)
» 21 Mar 2017 17:52:25.188 at Layer.handle (/var/app/current/node_modules/express/lib/router/layer.js:95:5)
» 21 Mar 2017 17:52:25.188 at Layer.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
» 21 Mar 2017 17:52:25.188 at Layer.wrappedLayerHandleRequest [as handle_request] (/var/app/current/node_modules/newrelic/lib/instrumentation/express.js:364:14)
» 21 Mar 2017 17:52:25.188 at /var/app/current/node_modules/express/lib/router/index.js:281:22
» 21 Mar 2017 17:52:25.188 at param (/var/app/current/node_modules/express/lib/router/index.js:354:14)
» 21 Mar 2017 17:52:25.188 at param (/var/app/current/node_modules/express/lib/router/index.js:365:14)`

**Comment by danielmontenegro** [comment]
Same error here! Any help would be priceless.

**Comment by LiorRabin** [comment]
@danielmontenegro does this occur on your local environment? for me it's just on AWS

**Comment by LiorRabin** [comment]
Ok, so I think I found the issue I'm facing.

If I use `loadtest -n 100 -c 20 http://local.mycompany.com:8888/api/test` I get the above warning.

If I comment-out `
self.on('disconnected', function () {
  return next();
});
` the warning does not happen anymore.

Question is why need this event if checking `if ( self.connected === false || self.client.connected === false ) {
          return next();
        }`

**Comment by Yurko-Fedoriv** [comment]
@LiorRabin thanks a lot, your solution helps.

**Comment by taysloane** [comment]
I just experienced this memory leak in production, pretty rapidly increasing RAM usage on one of our high-load servers. #86 fixed it—saved me a ton of time debugging, thanks! 🙏

**Comment by bharatzvm** [comment]
@LiorRabin 
`self.on('disconnected', function () { return next(); });`
Prevents the request from staling(request timeout) if disconnect happens while fetching from redis.

Instead of commenting it out why not use [on-finished ](https://github.com/jshttp/on-finished) and remove the event-listener.

**Comment by LiorRabin** [comment]
fixed by #86 so closing the issue
