### ISSUE TITLE
Allow choice of redis client

### ISSUE THREAD

**Issue by sedouard** [rv-kip/express-redis-cache#87]
This would be much more useful for production scenarios utilizing redis sentinels if a redis client was taken as an input. This way you can use `redis` or `ioredis` client libraries as they expose similar interfaces.

**Comment by weisjohn** [comment]
It looks like the README says you can do this:

>  You can pass a Redis client as well:
```javascript
require('express-redis-cache')({ client: require('redis').createClient() })
```

**Comment by Balgorn** [comment]
The problem by doing so is if you are use `ioredis` as a client ( my use case is to use redis-cluster) the middleware can`t create new cache entries and just pipes it to the next middleware.

**Comment by dam1** [comment]
Take a look here https://github.com/rv-kip/express-redis-cache/pull/98

**Comment by krazyjakee** [comment]
Closing for now
