### ISSUE TITLE
Error: Can't set headers after they are sent. 

### ISSUE THREAD

**Issue by wellcaffeinated** [rv-kip/express-redis-cache#92]
I see your comment in route.js (took me a while to figure this out)

https://github.com/rv-kip/express-redis-cache/blob/master/lib/ExpressRedisCache/route.js#L85

But... how do i get rid of this error? I still don't understand quite what's going on?

**Comment by krazyjakee** [comment]
Paste the full error so we can understand.

My theory is that you are sending a response and then trying to change response values.

This is old so am going to close it for now.
